# Generated by Django 4.1.7 on 2024-10-06 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_credits_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2024, 10, 6, 13, 50, 39, 156140, tzinfo=datetime.timezone.utc), verbose_name='Transaktionsdatum')),
                ('number', models.BigIntegerField(verbose_name='Anzahl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kauftransaktion',
                'verbose_name_plural': 'Kauftransaktionen',
            },
        ),
    ]
