# Generated by Django 4.1.7 on 2024-10-06 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_purchasetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Transaktionsdatum'),
        ),
    ]
