# Generated by Django 5.1.1 on 2024-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_purchasetransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('final', 'Abgeschlossen')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
