# Generated by Django 4.2 on 2026-04-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_purchasetransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Stripe Session ID'),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Stripe Payment Intent'),
        ),
    ]
