# Generated by Django 5.1.1 on 2024-09-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.categorie', verbose_name='Kategorie'),
        ),
    ]
