# Generated by Django 5.1.1 on 2024-09-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courses_date_alter_courses_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='categorie',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 10, 6, 2, 924598, tzinfo=datetime.timezone.utc)),
        ),
    ]
