# Generated by Django 5.1.1 on 2024-09-29 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_courses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 29, 22, 14, 21, 137399, tzinfo=datetime.timezone.utc)),
        ),
    ]
