# Generated by Django 5.1.1 on 2024-09-29 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_courses_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['date'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AddField(
            model_name='courses',
            name='capacity',
            field=models.BigIntegerField(default=7, verbose_name='Anzahl Plätze'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start',
            field=models.TimeField(default='18:00:00', verbose_name='Start Zeit'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Thema'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buchungsdatum')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kundin')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['date'],
            },
        ),
    ]
