# Generated by Django 4.1.7 on 2024-10-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_category_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='course.courses', verbose_name='Kurs'),
        ),
    ]
